server:
  port: ${PORT:8080}

spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smartscan_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:Postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB