server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartscan_db
    username: postgres
    password: Postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB